language: c
compiler: clang
install:
 - pip install --user --upgrade pip
 - pip install --user scikit-build
 - pip install --user ninja ninja-syntax
 - pip install --user git+https://github.com/Maratyszcza/PeachPy
 - pip install --user git+https://github.com/Maratyszcza/confu
before_script:
 - confu setup
 - python ./configure.py --backend=psimd
 - ninja
script:
 - ninja smoketest
addons:
  apt:
    packages:
    - linux-headers-3.13.0-40-generic
    - python-pip
