language: c
compiler: clang
install:
 - git clone https://github.com/ninja-build/ninja.git /tmp/ninja
 - pushd /tmp/ninja
 - git checkout release
 - python configure.py --bootstrap
 - export PATH=/tmp/ninja:$PATH
 - export PYTHONPATH=/tmp/ninja/misc
 - popd
before_script:
 - python ./configure.py --enable-psimd
script:
 - ninja
addons:
  apt:
    packages:
    - linux-headers-3.13.0-40-generic
