language: c
compiler: clang
install:
 - wget https://raw.githubusercontent.com/Maratyszcza/confu/master/install_deps.sh
 - bash ./install_deps.sh
 - export PATH=$HOME/.local/bin:$PATH
 - pip install --user ninja-syntax pyyaml
 - pip install --user git+https://github.com/Maratyszcza/PeachPy
 - pip install --user git+https://github.com/Maratyszcza/confu
before_script:
 - confu setup
 - python ./configure.py --backend=psimd
 - ninja
script:
 - ninja smoketest
addons:
  apt:
    packages:
    - linux-headers-3.13.0-40-generic
    - python-pip
