dist: trusty
language: c
compiler: clang
install:
 - git clone https://github.com/ninja-build/ninja.git /tmp/ninja
 - pushd /tmp/ninja
 - git checkout release
 - python configure.py --bootstrap
 - export PATH=/tmp/ninja:$PATH
 - popd
 - pip install --user ninja-syntax
 - pip install --user git+https://github.com/Maratyszcza/PeachPy
 - pip install --user git+https://github.com/Maratyszcza/confu
before_script:
 - confu setup
 - python ./configure.py --backend=psimd
 - ninja
script:
 - ninja smoketest
addons:
  apt:
    packages:
    - linux-headers-3.13.0-40-generic
    - python-pip
    - libgit2-dev
