language: c
compiler: clang
install:
 - pip install --user ninja-syntax
before_script:
 - python ./configure.py --enable-psimd
script: ninja
addons:
  apt:
    packages:
    - ninja-build
    - python-pip
